---
# Standards: 0.2
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ssh-almalinux8
    image: dokken/almalinux-8
    pre_build_image: true
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    capabilities:
      - CAP_NET_BIND_SERVICE
    published_ports:
      - 127.0.0.1:2258:22
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer
      stdout_callback: yaml
      executable: /bin/bash
  playbooks:
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
verifier:
  name: ansible
...
